let produce = [
    {
      id: 1,
      title: "queen panel bed",
      price: 10.99,
      src: "./images/product-1.jpeg",      
      numInBasket: 0,
      inBasket: false,
      numInStock: 12,
    },
    {
      id: 2,
      title: "king panel bed",
      price: 12.99,
      src: "./images/product-2.jpeg",
      numInBasket: 0,
      inBasket: false,
      numInStock: 15,
    },
    {
      id: 3,
      title: "single panel bed",
      price: 12.99,
      src: "./images/product-3.jpeg",
      numInBasket: 0,
      inBasket: false,
      numInStock: 13,
    },
    {
      id: 4,
      title: "twin panel bed",
      price: 22.99,
      src: "./images/product-4.jpeg",
      numInBasket: 0,
      inBasket: false,
      numInStock: 14,
    },
    {
      id: 5,
      title: "fridge",
      price: 88.99,
      src: "./images/product-5.jpeg",
      numInBasket: 0,
      inBasket: false,
      numInStock: 10,
    },
    {
      id: 6,
      title: "dresser",
      price: 32.99,
      src: "./images/product-6.jpeg",
      numInBasket: 0,
      inBasket: false,
      numInStock: 0,
    },
    {
      id: 7,
      title: "couch",
      price: 45.99,
      src: "./images/product-7.jpeg",
      numInBasket: 0,
      inBasket: false,
      numInStock: 20,
    },
    {
      id: 8,
      title: "table",
      price: 33.99,
      src: "./images/product-8.jpeg",
      numInBasket: 0,
      inBasket: false,
      numInStock: 25,
    },
  ];